### ISSUE TITLE
Usability problems

### ISSUE THREAD

**Issue by polarbearing** [praszuk/josm-fastdriveway-plugin#3]
Tested the plugin today, but I wonder where the advantage is for productivity. 
I have to draw the way and select it with the mouse, than change to the keyboard and press the combination. 

I have the same effect when I load the tagging values in the copy/paste buffer, and paste the values with the keyboard after drawing. 

In the config window, I miss:
* adding further values to the highway, e.g. ```access=``` or ```surface=```
* switching off the behaviuor to add a noxit node at the end. From my perspective, the end of a driveway is noexit by default. 

A better usability would be similar to the building plugin, the values are predefined in the config and added automatically when drawing, without having to switch between mouse and keyboard.

**Comment by praszuk** [comment]
> I have to draw the way and select it with the mouse, than change to the keyboard and press the combination.

When you draw the way, then it should be automatically selected, so you don't have to select it manually. It's an optional step, e.g. if you want to change different way. I don't understand what's wrong with using a mouse and keyboard at the same time, a lot of action in the JOSM probably requires it.

> I have the same effect when I load the tagging values in the copy/paste buffer, and paste the values with the keyboard after drawing.

If your case requires only `highway=service` `service=driveaway` yes, then you probably don't need it, but it does more :)

> where the advantage is for productivity.

I recommend to read [README.md](https://github.com/praszuk/josm-fastdriveway-plugin#driveway). The biggest advantage for me is creating `barrier=gate` on the fences intersections and ways auto-split with adding `access=private` to the second part, which improved significantly my productivity.

> adding further values to the highway, e.g. access= or surface=

You can add it to the first part (before `barrier=fence` in the config option). Just press enter and new table row should appear in the config window and you can add any tags you want. I don't support the second part of the way, because generally they are private possessions, they can have different surfaces etc., so I wanted to avoid errors.

> switching off the behaviuor to add a noxit node at the end. From my perspective, the end of a driveway is noexit by default.

I'm not sure if noexit is expected by default. It can help routing software and validators to avoid searching different paths nearby.

> A better usability would be similar to the building plugin, the values are predefined in the config and added automatically when drawing, without having to switch between mouse and keyboard.

Sorry, it would be too much effort to implement it, actually this plugin is something like my "hello-world" JOSM Plugin. I don't know for this moment if it will be developed further, but thank you for your opinion anyway.
